import { SidebarLink } from "@/types";
import {
  Store,
  FileDown,
  UserCog,
  User,
  Barcode,
  CpuIcon,
  BadgeDollarSign,
  Calendar,
  FileText,
  Drill,
  Headset,
  HandPlatter,
  Home,
} from "lucide-react";
import { z } from "zod";

export const themes = [
  { value: "light", label: "Light", icon: "icon/sun.svg" },
  { value: "dark", label: "Dark", icon: "icon/moon.svg" },
  { value: "system", label: "System", icon: "icon/computer.svg" },
];

export const sidebarLinks: SidebarLink[] = [
  {
    icon: Home,
    route: "/",
    desc: "Home page",
    label: "Home",
    options: [],
  },
  {
    icon: Store,
    route: "/merchant/find",
    desc: "Find MID, Agent, and Processor.",
    label: "Merchant",
    options: ["MID", "Agent", "Processor"],
  },
  {
    icon: Drill,
    route: "/equipment",
    desc: "Equipments",
    label: "Equipment",
    options: [],
  },
  {
    icon: Headset,
    route: "/agent",
    desc: "Agents",
    label: "Agent",
    options: [],
  },
  {
    icon: BadgeDollarSign,
    route: "/financial",
    desc: "Financial",
    label: "Financial",
    options: [],
  },
  {
    icon: HandPlatter,
    route: "/services",
    desc: "Services",
    label: "Services",
    options: [],
  },
  {
    icon: FileDown,
    route: "/fsp",
    desc: "Report the FSP",
    label: "FSP",
    options: ["FSP"],
  },
  {
    icon: UserCog,
    route: "/admin",
    desc: "Admin panel",
    label: "Admin",
    options: ["Admin"],
  },
];

export const profileLinks = [
  {
    title: "Profile",
    url: "/profile",
  },
  {
    title: "Settings",
    url: "/settings",
  },
  {
    title: "Logout",
    url: "/logout",
  },
];

export const merchantTabs = [
  {
    icons: Barcode,
    title: "MID",
    value: "mid",
  },
  {
    icons: User,
    title: "Agent",
    value: "agent",
  },
  {
    icons: CpuIcon,
    title: "Processor",
    value: "processor",
  },
  {
    icons: Calendar,
    title: "Created Date",
    value: "created_at",
  },
  {
    icons: FileText,
    title: "Reports",
    value: "reports",
  },
];

export const merchantMainTabs = [
  {
    title: "Find",
    value: "find",
    route: "/merchant/find"
  },
  {
    title: "Summary",
    value: "summary",
    route: "/merchant/summary"
  },
  {
    title: "Information",
    value: "information",
    route: "/merchant/information/info"
  },
  {
    title: "Reports",
    value: "reports",
    route: "/merchant/reports"
  }  
];
/**
 * This employees data is for mock-up data only!
 */
export const employees = [
  {
    EmployeeID: 1,
    FullName: "Nancy Davolio",
    Position: "Sales Representative",
    TitleOfCourtesy: "Ms.",
    BirthDate: "1968-12-08T00:00:00.000Z",
    HireDate: "2011-05-01T00:00:00.000Z",
    Address: "507 - 20th Ave. E.\r\nApt. 2A",
    City: "Seattle",
    Region: "WA",
    PostalCode: "98122",
    Country: "USA",
    HomePhone: "(206) 555-9857",
    Extension: "5467",
    Photo:
      "https://js.devexpress.com/Demos/WidgetsGallery/JSDemos/images/employees/06.png",
    Notes:
      'Education includes a BA in psychology from Colorado State University in 1990.  She also completed "The Art of the Cold Call."  Nancy is a member of Toastmasters International.',
    ReportsTo: 2,
  },
  {
    EmployeeID: 2,
    FullName: "Andrew Fuller",
    Position: "Vice President, Sales",
    TitleOfCourtesy: "Dr.",
    BirthDate: "1972-02-19T00:00:00.000Z",
    HireDate: "2011-08-14T00:00:00.000Z",
    Address: "908 W. Capital Way",
    City: "Tacoma",
    Region: "WA",
    PostalCode: "98401",
    Country: "USA",
    HomePhone: "(206) 555-9482",
    Extension: "3457",
    Photo:
      "https://js.devexpress.com/Demos/WidgetsGallery/JSDemos/images/employees/02.png",
    Notes:
      "Andrew received his BTS commercial in 1994 and a Ph.D. in international marketing from the University of Dallas in 2001.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 2012 and to vice president of sales in March 2013.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.",
    ReportsTo: null,
  },
  {
    EmployeeID: 3,
    FullName: "Janet Leverling",
    Position: "Sales Representative",
    TitleOfCourtesy: "Ms.",
    BirthDate: "1983-08-30T00:00:00.000Z",
    HireDate: "2011-04-01T00:00:00.000Z",
    Address: "722 Moss Bay Blvd.",
    City: "Kirkland",
    Region: "WA",
    PostalCode: "98033",
    Country: "USA",
    HomePhone: "(206) 555-3412",
    Extension: "3355",
    Photo:
      "https://js.devexpress.com/Demos/WidgetsGallery/JSDemos/images/employees/09.png",
    Notes:
      "Janet has a BS degree in chemistry from Boston College (2004).  She has also completed a certificate program in food retailing management.  Janet was hired as a sales associate in 2011 and promoted to sales representative in February 2012.",
    ReportsTo: 2,
  },
  {
    EmployeeID: 4,
    FullName: "Margaret Peacock",
    Position: "Sales Representative",
    TitleOfCourtesy: "Mrs.",
    BirthDate: "1957-09-19T00:00:00.000Z",
    HireDate: "2012-05-03T00:00:00.000Z",
    Address: "4110 Old Redmond Rd.",
    City: "Redmond",
    Region: "WA",
    PostalCode: "98052",
    Country: "USA",
    HomePhone: "(206) 555-8122",
    Extension: "5176",
    Photo:
      "https://js.devexpress.com/Demos/WidgetsGallery/JSDemos/images/employees/04.png",
    Notes:
      "Margaret holds a BA in English literature from Concordia College (1978) and an MA from the American Institute of Culinary Arts (1986).  She was assigned to the London office temporarily from July through November 2012.",
    ReportsTo: 2,
  },
  {
    EmployeeID: 5,
    FullName: "Steven Buchanan",
    Position: "Sales Manager",
    TitleOfCourtesy: "Mr.",
    BirthDate: "1975-03-04T00:00:00.000Z",
    HireDate: "2012-10-17T00:00:00.000Z",
    Address: "14 Garrett Hill",
    City: "London",
    Region: "UK",
    PostalCode: "SW1 8JR",
    Country: "UK",
    HomePhone: "(71) 555-4848",
    Extension: "3453",
    Photo:
      "https://js.devexpress.com/Demos/WidgetsGallery/JSDemos/images/employees/05.png",
    Notes:
      'Steven Buchanan graduated from St. Andrews University, Scotland, with a BSC degree in 1996.  Upon joining the company as a sales representative in 2012, he spent 6 months in an orientation program at the Seattle office and then returned to his permanent post in London.  He was promoted to sales manager in March 2013.  Mr. Buchanan has completed the courses "Successful Telemarketing" and "International Sales Management."  He is fluent in French.',
    ReportsTo: 2,
  },
  {
    EmployeeID: 6,
    FullName: "Michael Suyama",
    Position: "Sales Representative",
    TitleOfCourtesy: "Mr.",
    BirthDate: "1983-07-02T00:00:00.000Z",
    HireDate: "2012-10-17T00:00:00.000Z",
    Address: "Coventry House\r\nMiner Rd.",
    City: "London",
    Region: "UK",
    PostalCode: "EC2 7JR",
    Country: "UK",
    HomePhone: "(71) 555-7773",
    Extension: "428",
    Photo:
      "https://js.devexpress.com/Demos/WidgetsGallery/JSDemos/images/employees/01.png",
    Notes:
      'Michael is a graduate of Sussex University (MA, economics, 2003) and the University of California at Los Angeles (MBA, marketing, 2006). He has also taken the courses "Multi-Cultural Selling" and "Time Management for the Sales Professional."  He is fluent in Japanese and can read and write French, Portuguese, and Spanish.',
    ReportsTo: 5,
  },
  {
    EmployeeID: 7,
    FullName: "Robert King",
    Position: "Sales Representative",
    TitleOfCourtesy: "Mr.",
    BirthDate: "1980-05-29T00:00:00.000Z",
    HireDate: "2012-01-02T00:00:00.000Z",
    Address: "Edgeham Hollow\r\nWinchester Way",
    City: "London",
    Region: "UK",
    PostalCode: "RG1 9SP",
    Country: "UK",
    HomePhone: "(71) 555-5598",
    Extension: "465",
    Photo:
      "https://js.devexpress.com/Demos/WidgetsGallery/JSDemos/images/employees/07.png",
    Notes:
      'Robert King served in the Peace Corps and traveled extensively before completing his degree in English at the University of Michigan in 2002, the year he joined the company.  After completing a course entitled "Selling in Europe," he was transferred to the London office in March 2013.',
    ReportsTo: 5,
  },
  {
    EmployeeID: 8,
    FullName: "Laura Callahan",
    Position: "Inside Sales Coordinator",
    TitleOfCourtesy: "Ms.",
    BirthDate: "1978-01-09T00:00:00.000Z",
    HireDate: "2012-03-05T00:00:00.000Z",
    Address: "4726 - 11th Ave. N.E.",
    City: "Seattle",
    Region: "WA",
    PostalCode: "98105",
    Country: "USA",
    HomePhone: "(206) 555-1189",
    Extension: "2344",
    Photo:
      "https://js.devexpress.com/Demos/WidgetsGallery/JSDemos/images/employees/08.png",
    Notes:
      "Laura received a BA in psychology from the University of Washington.  She has also completed a course in business French.  She reads and writes French.",
    ReportsTo: 2,
  },
  {
    EmployeeID: 9,
    FullName: "Brett Wade",
    Position: "Sales Representative",
    TitleOfCourtesy: "Mr.",
    BirthDate: "1986-01-27T00:00:00.000Z",
    HireDate: "2012-11-15T00:00:00.000Z",
    Address: "7 Houndstooth Rd.",
    City: "London",
    Region: "UK",
    PostalCode: "WG2 7LT",
    Country: "UK",
    HomePhone: "(71) 555-4444",
    Extension: "452",
    Photo:
      "https://js.devexpress.com/Demos/WidgetsGallery/JSDemos/images/employees/03.png",
    Notes:
      "Brett has a BA degree in English from St. Lawrence College.  He is fluent in French and German.",
    ReportsTo: 5,
  },
];

export const equipmentData = [
  {
    id: 1,
    name: "Laptop",
    brand: "Dell",
    model: "XPS 15",
    purchaseDate: new Date("2021-01-15"),
    warrantyExpiration: new Date("2023-01-15"),
    status: "Operational",
    location: "Office A",
    assignedTo: "John Doe",
    price: 1500,
    serialNumber: "SN12345678",
  },
  {
    id: 2,
    name: "Monitor",
    brand: "Samsung",
    model: "Odyssey G9",
    purchaseDate: new Date("2020-12-05"),
    warrantyExpiration: new Date("2022-12-05"),
    status: "Operational",
    location: "Office B",
    assignedTo: "Jane Smith",
    price: 1200,
    serialNumber: "SN87654321",
  },
  {
    id: 3,
    name: "Printer",
    brand: "HP",
    model: "LaserJet Pro",
    purchaseDate: new Date("2019-08-20"),
    warrantyExpiration: new Date("2021-08-20"),
    status: "Operational",
    location: "Office C",
    assignedTo: "Bob Johnson",
    price: 300,
    serialNumber: "SN11223344",
  },
  {
    id: 4,
    name: "Router",
    brand: "Cisco",
    model: "RV340",
    purchaseDate: new Date("2018-05-10"),
    warrantyExpiration: new Date("2021-05-10"),
    status: "Operational",
    location: "Server Room",
    assignedTo: "IT Dept",
    price: 600,
    serialNumber: "SN55667788",
  },
  {
    id: 5,
    name: "Server",
    brand: "IBM",
    model: "X3650 M5",
    purchaseDate: new Date("2017-02-14"),
    warrantyExpiration: new Date("2020-02-14"),
    status: "Operational",
    location: "Data Center",
    assignedTo: "IT Dept",
    price: 5000,
    serialNumber: "SN99887766",
  },
  {
    id: 6,
    name: "Keyboard",
    brand: "Logitech",
    model: "MX Keys",
    purchaseDate: new Date("2020-09-30"),
    warrantyExpiration: new Date("2021-09-30"),
    status: "Operational",
    location: "Office A",
    assignedTo: "John Doe",
    price: 100,
    serialNumber: "SN33221144",
  },
  {
    id: 7,
    name: "Mouse",
    brand: "Logitech",
    model: "MX Master 3",
    purchaseDate: new Date("2020-09-30"),
    warrantyExpiration: new Date("2021-09-30"),
    status: "Operational",
    location: "Office B",
    assignedTo: "Jane Smith",
    price: 100,
    serialNumber: "SN44332211",
  },
  {
    id: 8,
    name: "Tablet",
    brand: "Apple",
    model: "iPad Pro",
    purchaseDate: new Date("2019-11-20"),
    warrantyExpiration: new Date("2021-11-20"),
    status: "Operational",
    location: "Office D",
    assignedTo: "Alice Green",
    price: 900,
    serialNumber: "SN55443322",
  },
  {
    id: 9,
    name: "Projector",
    brand: "Epson",
    model: "EB-X05",
    purchaseDate: new Date("2018-07-25"),
    warrantyExpiration: new Date("2021-07-25"),
    status: "Operational",
    location: "Conference Room",
    assignedTo: "IT Dept",
    price: 400,
    serialNumber: "SN66554433",
  },
  {
    id: 10,
    name: "Camera",
    brand: "Canon",
    model: "EOS 80D",
    purchaseDate: new Date("2017-10-15"),
    warrantyExpiration: new Date("2019-10-15"),
    status: "Operational",
    location: "Office E",
    assignedTo: "David White",
    price: 1000,
    serialNumber: "SN77665544",
  },
  {
    id: 11,
    name: "Laptop",
    brand: "Apple",
    model: "MacBook Pro",
    purchaseDate: new Date("2021-02-10"),
    warrantyExpiration: new Date("2023-02-10"),
    status: "Operational",
    location: "Office F",
    assignedTo: "Eve Brown",
    price: 2000,
    serialNumber: "SN88776655",
  },
  {
    id: 12,
    name: "Smartphone",
    brand: "Samsung",
    model: "Galaxy S21",
    purchaseDate: new Date("2021-04-01"),
    warrantyExpiration: new Date("2022-04-01"),
    status: "Operational",
    location: "Office G",
    assignedTo: "Charlie Black",
    price: 800,
    serialNumber: "SN99887744",
  },
  {
    id: 13,
    name: "Switch",
    brand: "Netgear",
    model: "GS308",
    purchaseDate: new Date("2020-06-15"),
    warrantyExpiration: new Date("2021-06-15"),
    status: "Operational",
    location: "Server Room",
    assignedTo: "IT Dept",
    price: 50,
    serialNumber: "SN11224433",
  },
  {
    id: 14,
    name: "Docking Station",
    brand: "Dell",
    model: "WD19",
    purchaseDate: new Date("2019-03-30"),
    warrantyExpiration: new Date("2021-03-30"),
    status: "Operational",
    location: "Office H",
    assignedTo: "Ivy Blue",
    price: 200,
    serialNumber: "SN22334455",
  },
  {
    id: 15,
    name: "Speakers",
    brand: "Bose",
    model: "Companion 2",
    purchaseDate: new Date("2018-11-05"),
    warrantyExpiration: new Date("2020-11-05"),
    status: "Operational",
    location: "Office I",
    assignedTo: "Jack Orange",
    price: 150,
    serialNumber: "SN33445566",
  },
  {
    id: 16,
    name: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad X1",
    purchaseDate: new Date("2021-08-19"),
    warrantyExpiration: new Date("2023-08-19"),
    status: "Operational",
    location: "Office J",
    assignedTo: "Grace Violet",
    price: 1700,
    serialNumber: "SN44556677",
  },
  {
    id: 17,
    name: "Headphones",
    brand: "Sony",
    model: "WH-1000XM4",
    purchaseDate: new Date("2020-12-15"),
    warrantyExpiration: new Date("2021-12-15"),
    status: "Operational",
    location: "Office K",
    assignedTo: "Ken Gold",
    price: 300,
    serialNumber: "SN55667788",
  },
  {
    id: 18,
    name: "Scanner",
    brand: "Brother",
    model: "ADS-2700W",
    purchaseDate: new Date("2019-05-25"),
    warrantyExpiration: new Date("2021-05-25"),
    status: "Operational",
    location: "Office L",
    assignedTo: "Helen Cyan",
    price: 400,
    serialNumber: "SN66778899",
  },
  {
    id: 19,
    name: "External HDD",
    brand: "Seagate",
    model: "Backup Plus",
    purchaseDate: new Date("2020-02-28"),
    warrantyExpiration: new Date("2021-02-28"),
    status: "Operational",
    location: "Server Room",
    assignedTo: "IT Dept",
    price: 100,
    serialNumber: "SN77889900",
  },
  {
    id: 20,
    name: "Projector",
    brand: "BenQ",
    model: "TK850",
    purchaseDate: new Date("2019-09-10"),
    warrantyExpiration: new Date("2021-09-10"),
    status: "Operational",
    location: "Conference Room",
    assignedTo: "IT Dept",
    price: 1200,
    serialNumber: "SN88990011",
  },
];

export const agentData = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1-555-1234",
    department: "Sales",
    status: "Active",
    location: "New York",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+1-555-5678",
    department: "Support",
    status: "Active",
    location: "Los Angeles",
  },
  {
    id: 3,
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    phone: "+1-555-8765",
    department: "Marketing",
    status: "Inactive",
    location: "Chicago",
  },
  {
    id: 4,
    name: "Alice Green",
    email: "alice.green@example.com",
    phone: "+1-555-4321",
    department: "Development",
    status: "Active",
    location: "San Francisco",
  },
  {
    id: 5,
    name: "Charlie Brown",
    email: "charlie.brown@example.com",
    phone: "+1-555-6789",
    department: "HR",
    status: "Inactive",
    location: "Houston",
  },
  {
    id: 6,
    name: "Eve Black",
    email: "eve.black@example.com",
    phone: "+1-555-9876",
    department: "Sales",
    status: "Active",
    location: "Phoenix",
  },
  {
    id: 7,
    name: "David White",
    email: "david.white@example.com",
    phone: "+1-555-5432",
    department: "Support",
    status: "Inactive",
    location: "Philadelphia",
  },
  {
    id: 8,
    name: "Helen Blue",
    email: "helen.blue@example.com",
    phone: "+1-555-6543",
    department: "Marketing",
    status: "Active",
    location: "San Antonio",
  },
  {
    id: 9,
    name: "Ken Yellow",
    email: "ken.yellow@example.com",
    phone: "+1-555-3456",
    department: "Development",
    status: "Active",
    location: "Dallas",
  },
  {
    id: 10,
    name: "Grace Red",
    email: "grace.red@example.com",
    phone: "+1-555-2345",
    department: "HR",
    status: "Inactive",
    location: "San Diego",
  },
];

// formField for dynamic fields
export const AgentSetupFields = [
  {
    name: "exludeClosedAgents",
    label: "Exclude Closed Agents",
    type: "checkbox",
    defaultValue: "",
    validation: z.string().nonempty("Display Name is required"),
  },
  {
    name: "findAgent",
    label: "Find Agent",
    type: "select",
    options: ["Agent 1", "Agent 2", "Agent 3"],
    defaultValue: "",
    validation: z.string().nonempty("Display Name is required"),
  },
  {
    name: "displayName",
    label: "Display Name",
    type: "text",
    defaultValue: "",
    validation: z.string().nonempty("Display Name is required"),
  },
  {
    name: "firstName",
    label: "First Name",
    type: "text",
    defaultValue: "",
    validation: z.string().nonempty("First Name is required"),
  },
  {
    name: "lastName",
    label: "Last Name",
    type: "text",
    defaultValue: "",
    validation: z.string().nonempty("Last Name is required"),
  },
  {
    name: "email",
    label: "Email",
    type: "email",
    defaultValue: "",
    validation: z.string().email("Invalid email address"),
  },
  {
    name: "status",
    label: "Status",
    type: "select",
    options: ["Active", "Inactive"],
    defaultValue: "",
    validation: z.string().nonempty("Status is required"),
  },
  {
    name: "startDate",
    label: "Start Date",
    type: "date",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "endDate",
    label: "End Date",
    type: "date",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "address1",
    label: "Address 1",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "address2",
    label: "Address 2",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "city",
    label: "City",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "state",
    label: "State",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "zip",
    label: "Zip",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "routing",
    label: "Routing #",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "account",
    label: "Account #",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "ssn",
    label: "SSN / EIN",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "payDay",
    label: "Pay Day",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "payGroup",
    label: "Pay Group",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "msoId",
    label: "MSO ID",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "reportType",
    label: "Report Type",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "payrollId",
    label: "Payroll ID",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "agentId",
    label: "Agent ID",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "note",
    label: "Note",
    type: "textarea",
    defaultValue: "",
    validation: z.string().optional(),
  },
];

export const agentLeadSourceDataTable = [
  {
    SalesRep: "Liam Johnson",
    "Split %": "100%",
    Master: "XX",
    "A/M": "",
    "F/M": "",
    "A/A": "",
    R: "",
    "F/SM": "",
  },
  {
    SalesRep: "Eric Smith",
    "Split %": "4%",
    Master: "XX",
    "A/M": "",
    "F/M": "",
    "A/A": "",
    R: "",
    "F/SM": "",
  },
]
