import { DataTypes, SidebarLink } from "@/types";
import {
  Store,
  FileDown,
  UserCog,
  User,
  Barcode,
  CpuIcon,
  BadgeDollarSign,
  Calendar,
  FileText,
  Drill,
  Headset,
  HandPlatter,
  Home,
} from "lucide-react";
import { z } from "zod";

export const themes = [
  { value: "light", label: "Light", icon: "icon/sun.svg" },
  { value: "dark", label: "Dark", icon: "icon/moon.svg" },
  { value: "system", label: "System", icon: "icon/computer.svg" },
];

export const sidebarLinks: SidebarLink[] = [
  {
    icon: Home,
    route: "/",
    desc: "Home page",
    label: "Home",
    options: [],
  },
  {
    icon: Store,
    route: "/merchant/find",
    desc: "Find MID, Agent, and Processor.",
    label: "Merchant",
    options: ["MID", "Agent", "Processor"],
  },
  {
    icon: Drill,
    route: "/equipment",
    desc: "Equipments",
    label: "Equipment",
    options: [],
  },
  {
    icon: Headset,
    route: "/agent",
    desc: "Agents",
    label: "Agent",
    options: [],
  },
  {
    icon: BadgeDollarSign,
    route: "/financial",
    desc: "Financial",
    label: "Financial",
    options: [],
  },
  {
    icon: HandPlatter,
    route: "/services",
    desc: "Services",
    label: "Services",
    options: [],
  },
  {
    icon: FileDown,
    route: "/fsp",
    desc: "Report the FSP",
    label: "FSP",
    options: ["FSP"],
  },
  {
    icon: UserCog,
    route: "/admin",
    desc: "Admin panel",
    label: "Admin",
    options: ["Admin"],
  },
];

export const profileLinks = [
  {
    title: "Profile",
    url: "/profile",
  },
  {
    title: "Settings",
    url: "/settings",
  },
  {
    title: "Logout",
    url: "/logout",
  },
];

export const merchantTabs = [
  {
    icons: Barcode,
    title: "MID",
    value: "mid",
  },
  {
    icons: User,
    title: "Agent",
    value: "agent",
  },
  {
    icons: CpuIcon,
    title: "Processor",
    value: "processor",
  },
  {
    icons: Calendar,
    title: "Created Date",
    value: "created_at",
  },
  {
    icons: FileText,
    title: "Reports",
    value: "reports",
  },
];

export const merchantMainTabs = [
  {
    title: "Find",
    value: "find",
    route: "/merchant/find",
  },
  {
    title: "Summary",
    value: "summary",
    route: "/merchant/summary",
  },
  {
    title: "Information",
    value: "information",
    route: "/merchant/information/info",
  },
  {
    title: "Reports",
    value: "reports",
    route: "/merchant/reports",
  },
];

export const tabItems = [
  {
    id: "1",
    title: "Information",
    value: "information",
    route: "/merchant/information/info",
  },
  {
    id: "2",
    title: "Access One API",
    value: "accessoneapi",
    route: "/merchant/information/accessoneapi",
  },
  {
    id: "3",
    title: "Agent / Lead Source",
    value: "agentleadsource",
    route: "/merchant/information/agentleadsource",
  },
  {
    id: "4",
    title: "Account Status",
    value: "accountstatus",
    route: "/merchant/information/accountstatus",
  },
  {
    id: "5",
    title: "Call Log / Tasks",
    value: "calllog",
    route: "/merchant/information/calllog",
  },
  {
    id: "6",
    title: "ZenDesk(1)",
    value: "zendesk",
    route: "/merchant/information/zendesk",
  },
  {
    id: "7",
    title: "Leasing",
    value: "leasing",
    route: "/merchant/information/leasing",
  },
  {
    id: "8",
    title: "Equipment",
    value: "equipment",
    route: "/merchant/information/equipment",
  },
  {
    id: "9",
    title: "Onboard Checklist",
    value: "onboardchecklist",
    route: "/merchant/information/onboardchecklist",
  },
  {
    id: "10",
    title: "Documents",
    value: "documents",
    route: "/merchant/information/documents",
  },
  {
    id: "11",
    title: "Merch Fees / Proc",
    value: "merchfees",
    route: "/merchant/information/merchfees",
  },
  {
    id: "12",
    title: "Software Install",
    value: "softwareinstall",
    route: "/merchant/information/softwareinstall",
  },
  {
    id: "13",
    title: "Reject / Collections",
    value: "rejectcollections",
    route: "/merchant/information/rejectcollections",
  },
  {
    id: "14",
    title: "Residuals",
    value: "residuals",
    route: "/merchant/information/residuals",
  },
  {
    id: "15",
    title: "WAVit Info",
    value: "wavitInfo",
    route: "/merchant/information/wavitinfo",
  },
  {
    id: "16",
    title: "BOTWest",
    value: "botWest",
    route: "/merchant/information/botwest",
  },
];
/**
 * This employees data is for mock-up data only!
 */
export const employees: DataTypes[] = [
  {
    EmployeeID: 1,
    FullName: "Nancy Davolio",
    Address: "507 - 20th Ave. E.\r\nApt. 2A",
    City: "Seattle",
    Region: "WA",
    PostalCode: "98122",
    Country: "USA",
    HomePhone: "(206) 555-9857",
    Position: "Sales Representative",
    BirthDate: new Date("1968-12-08T00:00:00.000Z"),
  },
  {
    EmployeeID: 2,
    FullName: "Andrew Fuller",
    Address: "908 W. Capital Way",
    City: "Tacoma",
    Region: "WA",
    PostalCode: "98401",
    Country: "USA",
    HomePhone: "(206) 555-9482",
    Position: "Vice President, Sales",
    BirthDate: new Date("1972-02-19T00:00:00.000Z"),
  },
  {
    EmployeeID: 3,
    FullName: "Janet Leverling",
    Address: "722 Moss Bay Blvd.",
    City: "Kirkland",
    Region: "WA",
    PostalCode: "98033",
    Country: "USA",
    HomePhone: "(206) 555-3412",
    Position: "Sales Representative",
    BirthDate: new Date("1983-08-30T00:00:00.000Z"),
  },
  {
    EmployeeID: 4,
    FullName: "Margaret Peacock",
    Address: "4110 Old Redmond Rd.",
    City: "Redmond",
    Region: "WA",
    PostalCode: "98052",
    Country: "USA",
    HomePhone: "(206) 555-8122",
    Position: "Sales Representative",
    BirthDate: new Date("1980-09-19T00:00:00.000Z"),
  },
  {
    EmployeeID: 5,
    FullName: "Steven Buchanan",
    Address: "14 Garrett Hill",
    City: "London",
    Region: "",
    PostalCode: "SW1 8JR",
    Country: "UK",
    HomePhone: "(71) 555-4848",
    Position: "Sales Manager",
    BirthDate: new Date("1966-03-04T00:00:00.000Z"),
  },
  {
    EmployeeID: 6,
    FullName: "Michael Suyama",
    Address: "Coventry House\r\nMiner Rd.",
    City: "London",
    Region: "",
    PostalCode: "EC2 7JR",
    Country: "UK",
    HomePhone: "(71) 555-7773",
    Position: "Sales Representative",
    BirthDate: new Date("1963-07-02T00:00:00.000Z"),
  },
  {
    EmployeeID: 7,
    FullName: "Robert King",
    Address: "Edgeham Hollow\r\nWinchester Way",
    City: "London",
    Region: "",
    PostalCode: "RG1 9SP",
    Country: "UK",
    HomePhone: "(71) 555-5598",
    Position: "Sales Representative",
    BirthDate: new Date("1984-05-29T00:00:00.000Z"),
  },
  {
    EmployeeID: 8,
    FullName: "Laura Callahan",
    Address: "4726 - 11th Ave. N.E.",
    City: "Seattle",
    Region: "WA",
    PostalCode: "98105",
    Country: "USA",
    HomePhone: "(206) 555-1189",
    Position: "Inside Sales Coordinator",
    BirthDate: new Date("1988-01-09T00:00:00.000Z"),
  },
  {
    EmployeeID: 9,
    FullName: "Anne Dodsworth",
    Address: "7 Houndstooth Rd.",
    City: "London",
    Region: "",
    PostalCode: "WG2 7LT",
    Country: "UK",
    HomePhone: "(71) 555-4444",
    Position: "Sales Representative",
    BirthDate: new Date("1974-01-27T00:00:00.000Z"),
  },
  {
    EmployeeID: 10,
    FullName: "Tim Lee",
    Address: "123 Maple St.",
    City: "Dallas",
    Region: "TX",
    PostalCode: "75201",
    Country: "USA",
    HomePhone: "(214) 555-7890",
    Position: "Sales Manager",
    BirthDate: new Date("1976-11-10T00:00:00.000Z"),
  },
];

export const equipmentData: DataTypes[] = [
  {
    id: 1,
    name: "Laptop",
    brand: "Dell",
    model: "XPS 15",
    purchaseDate: new Date("2021-01-15"),
    warrantyExpiration: new Date("2023-01-15"),
    status: "Operational",
    location: "Office A",
    assignedTo: "John Doe",
    price: 1500,
    serialNumber: "SN12345678",
  },
  {
    id: 2,
    name: "Monitor",
    brand: "Samsung",
    model: "Odyssey G9",
    purchaseDate: new Date("2020-12-05"),
    warrantyExpiration: new Date("2022-12-05"),
    status: "Operational",
    location: "Office B",
    assignedTo: "Jane Smith",
    price: 1200,
    serialNumber: "SN87654321",
  },
  {
    id: 3,
    name: "Printer",
    brand: "HP",
    model: "LaserJet Pro",
    purchaseDate: new Date("2019-08-20"),
    warrantyExpiration: new Date("2021-08-20"),
    status: "Operational",
    location: "Office C",
    assignedTo: "Bob Johnson",
    price: 300,
    serialNumber: "SN11223344",
  },
  {
    id: 4,
    name: "Router",
    brand: "Cisco",
    model: "RV340",
    purchaseDate: new Date("2018-05-10"),
    warrantyExpiration: new Date("2021-05-10"),
    status: "Operational",
    location: "Server Room",
    assignedTo: "IT Dept",
    price: 600,
    serialNumber: "SN55667788",
  },
  {
    id: 5,
    name: "Server",
    brand: "IBM",
    model: "X3650 M5",
    purchaseDate: new Date("2017-02-14"),
    warrantyExpiration: new Date("2020-02-14"),
    status: "Operational",
    location: "Data Center",
    assignedTo: "IT Dept",
    price: 5000,
    serialNumber: "SN99887766",
  },
  {
    id: 6,
    name: "Keyboard",
    brand: "Logitech",
    model: "MX Keys",
    purchaseDate: new Date("2020-09-30"),
    warrantyExpiration: new Date("2021-09-30"),
    status: "Operational",
    location: "Office A",
    assignedTo: "John Doe",
    price: 100,
    serialNumber: "SN33221144",
  },
  {
    id: 7,
    name: "Mouse",
    brand: "Logitech",
    model: "MX Master 3",
    purchaseDate: new Date("2020-09-30"),
    warrantyExpiration: new Date("2021-09-30"),
    status: "Operational",
    location: "Office B",
    assignedTo: "Jane Smith",
    price: 100,
    serialNumber: "SN44332211",
  },
  {
    id: 8,
    name: "Tablet",
    brand: "Apple",
    model: "iPad Pro",
    purchaseDate: new Date("2019-11-20"),
    warrantyExpiration: new Date("2021-11-20"),
    status: "Operational",
    location: "Office D",
    assignedTo: "Alice Green",
    price: 900,
    serialNumber: "SN55443322",
  },
  {
    id: 9,
    name: "Projector",
    brand: "Epson",
    model: "EB-X05",
    purchaseDate: new Date("2018-07-25"),
    warrantyExpiration: new Date("2021-07-25"),
    status: "Operational",
    location: "Conference Room",
    assignedTo: "IT Dept",
    price: 400,
    serialNumber: "SN66554433",
  },
  {
    id: 10,
    name: "Camera",
    brand: "Canon",
    model: "EOS 80D",
    purchaseDate: new Date("2017-10-15"),
    warrantyExpiration: new Date("2019-10-15"),
    status: "Operational",
    location: "Office E",
    assignedTo: "David White",
    price: 1000,
    serialNumber: "SN77665544",
  },
  {
    id: 11,
    name: "Laptop",
    brand: "Apple",
    model: "MacBook Pro",
    purchaseDate: new Date("2021-02-10"),
    warrantyExpiration: new Date("2023-02-10"),
    status: "Operational",
    location: "Office F",
    assignedTo: "Eve Brown",
    price: 2000,
    serialNumber: "SN88776655",
  },
  {
    id: 12,
    name: "Smartphone",
    brand: "Samsung",
    model: "Galaxy S21",
    purchaseDate: new Date("2021-04-01"),
    warrantyExpiration: new Date("2022-04-01"),
    status: "Operational",
    location: "Office G",
    assignedTo: "Charlie Black",
    price: 800,
    serialNumber: "SN99887744",
  },
  {
    id: 13,
    name: "Switch",
    brand: "Netgear",
    model: "GS308",
    purchaseDate: new Date("2020-06-15"),
    warrantyExpiration: new Date("2021-06-15"),
    status: "Operational",
    location: "Server Room",
    assignedTo: "IT Dept",
    price: 50,
    serialNumber: "SN11224433",
  },
  {
    id: 14,
    name: "Docking Station",
    brand: "Dell",
    model: "WD19",
    purchaseDate: new Date("2019-03-30"),
    warrantyExpiration: new Date("2021-03-30"),
    status: "Operational",
    location: "Office H",
    assignedTo: "Ivy Blue",
    price: 200,
    serialNumber: "SN22334455",
  },
  {
    id: 15,
    name: "Speakers",
    brand: "Bose",
    model: "Companion 2",
    purchaseDate: new Date("2018-11-05"),
    warrantyExpiration: new Date("2020-11-05"),
    status: "Operational",
    location: "Office I",
    assignedTo: "Jack Orange",
    price: 150,
    serialNumber: "SN33445566",
  },
  {
    id: 16,
    name: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad X1",
    purchaseDate: new Date("2021-08-19"),
    warrantyExpiration: new Date("2023-08-19"),
    status: "Operational",
    location: "Office J",
    assignedTo: "Grace Violet",
    price: 1700,
    serialNumber: "SN44556677",
  },
  {
    id: 17,
    name: "Headphones",
    brand: "Sony",
    model: "WH-1000XM4",
    purchaseDate: new Date("2020-12-15"),
    warrantyExpiration: new Date("2021-12-15"),
    status: "Operational",
    location: "Office K",
    assignedTo: "Ken Gold",
    price: 300,
    serialNumber: "SN55667788",
  },
  {
    id: 18,
    name: "Scanner",
    brand: "Brother",
    model: "ADS-2700W",
    purchaseDate: new Date("2019-05-25"),
    warrantyExpiration: new Date("2021-05-25"),
    status: "Operational",
    location: "Office L",
    assignedTo: "Helen Cyan",
    price: 400,
    serialNumber: "SN66778899",
  },
  {
    id: 19,
    name: "External HDD",
    brand: "Seagate",
    model: "Backup Plus",
    purchaseDate: new Date("2020-02-28"),
    warrantyExpiration: new Date("2021-02-28"),
    status: "Operational",
    location: "Server Room",
    assignedTo: "IT Dept",
    price: 100,
    serialNumber: "SN77889900",
  },
  {
    id: 20,
    name: "Projector",
    brand: "BenQ",
    model: "TK850",
    purchaseDate: new Date("2019-09-10"),
    warrantyExpiration: new Date("2021-09-10"),
    status: "Operational",
    location: "Conference Room",
    assignedTo: "IT Dept",
    price: 1200,
    serialNumber: "SN88990011",
  },
];

export const agentData: DataTypes[] = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1-555-1234",
    department: "Sales",
    status: "Active",
    location: "New York",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+1-555-5678",
    department: "Support",
    status: "Active",
    location: "Los Angeles",
  },
  {
    id: 3,
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    phone: "+1-555-8765",
    department: "Marketing",
    status: "Inactive",
    location: "Chicago",
  },
  {
    id: 4,
    name: "Alice Green",
    email: "alice.green@example.com",
    phone: "+1-555-4321",
    department: "Development",
    status: "Active",
    location: "San Francisco",
  },
  {
    id: 5,
    name: "Charlie Brown",
    email: "charlie.brown@example.com",
    phone: "+1-555-6789",
    department: "HR",
    status: "Inactive",
    location: "Houston",
  },
  {
    id: 6,
    name: "Eve Black",
    email: "eve.black@example.com",
    phone: "+1-555-9876",
    department: "Sales",
    status: "Active",
    location: "Phoenix",
  },
  {
    id: 7,
    name: "David White",
    email: "david.white@example.com",
    phone: "+1-555-5432",
    department: "Support",
    status: "Inactive",
    location: "Philadelphia",
  },
  {
    id: 8,
    name: "Helen Blue",
    email: "helen.blue@example.com",
    phone: "+1-555-6543",
    department: "Marketing",
    status: "Active",
    location: "San Antonio",
  },
  {
    id: 9,
    name: "Ken Yellow",
    email: "ken.yellow@example.com",
    phone: "+1-555-3456",
    department: "Development",
    status: "Active",
    location: "Dallas",
  },
  {
    id: 10,
    name: "Grace Red",
    email: "grace.red@example.com",
    phone: "+1-555-2345",
    department: "HR",
    status: "Inactive",
    location: "San Diego",
  },
];

export const Orders: DataTypes[] = [
  {
    id: 1,
    customer: "Liam Johnson",
    email: "liam@example.com",
    type: "Sale",
    status: "Fulfilled",
    date: "2023-06-23",
    amount: "$250.00",
  },
  {
    id: 2,
    customer: "Emma Wilson",
    email: "emma@example.com",
    type: "Purchase",
    status: "Pending",
    date: "2023-06-24",
    amount: "$150.00",
  },
  {
    id: 3,
    customer: "Noah Brown",
    email: "noah@example.com",
    type: "Sale",
    status: "Shipped",
    date: "2023-06-25",
    amount: "$300.00",
  },
  {
    id: 4,
    customer: "Olivia Davis",
    email: "olivia@example.com",
    type: "Return",
    status: "Processed",
    date: "2023-06-26",
    amount: "$50.00",
  },
  {
    id: 5,
    customer: "James Miller",
    email: "james@example.com",
    type: "Purchase",
    status: "Cancelled",
    date: "2023-06-27",
    amount: "$200.00",
  },
  {
    id: 6,
    customer: "Sophia Martinez",
    email: "sophia@example.com",
    type: "Sale",
    status: "Denied",
    date: "2023-06-28",
    amount: "$400.00",
  },
  {
    id: 7,
    customer: "Benjamin Anderson",
    email: "benjamin@example.com",
    type: "Return",
    status: "Pending",
    date: "2023-06-29",
    amount: "$75.00",
  },
  {
    id: 8,
    customer: "Isabella Hernandez",
    email: "isabella@example.com",
    type: "Purchase",
    status: "Pending",
    date: "2023-06-30",
    amount: "$500.00",
  },
  {
    id: 9,
    customer: "Lucas Moore",
    email: "lucas@example.com",
    type: "Sale",
    status: "Success",
    date: "2023-07-01",
    amount: "$350.00",
  },
  {
    id: 10,
    customer: "Mia Taylor",
    email: "mia@example.com",
    type: "Purchase",
    status: "Success",
    date: "2023-07-02",
    amount: "$100.00",
  },
];

//
//
// formField for dynamic fields
export const AgentSetupFields = [
  {
    name: "exludeClosedAgents",
    label: "Exclude Closed Agents",
    type: "checkbox",
    defaultValue: "",
    validation: z.string().nonempty("Display Name is required"),
  },
  {
    name: "findAgent",
    label: "Find Agent",
    type: "select",
    options: ["Agent 1", "Agent 2", "Agent 3"],
    defaultValue: "",
    validation: z.string().nonempty("Display Name is required"),
  },
  {
    name: "displayName",
    label: "Display Name",
    type: "text",
    defaultValue: "",
    validation: z.string().nonempty("Display Name is required"),
  },
  {
    name: "firstName",
    label: "First Name",
    type: "text",
    defaultValue: "",
    validation: z.string().nonempty("First Name is required"),
  },
  {
    name: "lastName",
    label: "Last Name",
    type: "text",
    defaultValue: "",
    validation: z.string().nonempty("Last Name is required"),
  },
  {
    name: "email",
    label: "Email",
    type: "email",
    defaultValue: "",
    validation: z.string().email("Invalid email address"),
  },
  {
    name: "status",
    label: "Status",
    type: "select",
    options: ["Active", "Inactive"],
    defaultValue: "",
    validation: z.string().nonempty("Status is required"),
  },
  {
    name: "startDate",
    label: "Start Date",
    type: "date",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "endDate",
    label: "End Date",
    type: "date",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "address1",
    label: "Address 1",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "address2",
    label: "Address 2",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "city",
    label: "City",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "state",
    label: "State",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "zip",
    label: "Zip",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "routing",
    label: "Routing #",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "account",
    label: "Account #",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "ssn",
    label: "SSN / EIN",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "payDay",
    label: "Pay Day",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "payGroup",
    label: "Pay Group",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "msoId",
    label: "MSO ID",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "reportType",
    label: "Report Type",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "payrollId",
    label: "Payroll ID",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "agentId",
    label: "Agent ID",
    type: "text",
    defaultValue: "",
    validation: z.string().optional(),
  },
  {
    name: "note",
    label: "Note",
    type: "textarea",
    defaultValue: "",
    validation: z.string().optional(),
  },
];

export const AgentSetupTabs = [
  {
    id: "1",
    title: "Residuals",
    value: "residuals",
  },
  {
    id: "2",
    title: "Billing",
    value: "billing",
  },
  {
    id: "3",
    title: "Customer Finance",
    value: "customerFinance",
  },
  {
    id: "4",
    title: "Equipment",
    value: "equipment",
  },
  {
    id: "5",
    title: "Documentation",
    value: "documentation",
  },
  {
    id: "6",
    title: "Reporting",
    value: "reporting",
  },
  {
    id: "7",
    title: "Email Lists",
    value: "emailList",
  },
  {
    id: "8",
    title: "Adjustments",
    value: "adjustments",
  },
];

export const FindAgent = [
  { id: 1, name: "Average Joe", value: "avgJoe" },
  { id: 2, name: "Martin Joe", value: "marJoe" },
];

export const SubAgentOrChild = [
  { id: 1, name: "Testing1", value: "test1" },
  { id: 2, name: "Testing2", value: "test2" },
  { id: 3, name: "Testing3", value: "test3" },
];

export const summaryItems = [
  {
    title: "MID",
    value: "518991561321",
  },
  {
    title: "Legal Name",
    value: "MiCamp Solutions",
  },
  {
    title: "DBA",
    value: "Tony Stark",
  },
  {
    title: "Agent",
    value: "007 Somewhere Rd",
  },
  {
    title: "Processor",
    value: "First Data Omaha",
  },
  {
    title: "Costumer Service Email",
    value: "support@micamp.com",
  },
  {
    title: "Current Status",
    value: "Approved",
  },
  {
    title: "Notices",
    value: "No notices yet",
  },
  {
    title: "Product",
    value: "Some product",
  },
  {
    title: "ID",
    value: "3952",
  },
  {
    title: "WAVit Account",
    value: "PIN: 9847",
  },
];
